# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  setup:

    name: Build and Deploy
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.18.2
      with:
        elixir-version: '1.18.1' # [Required] Define the Elixir version
        otp-version: '27.0'      # [Required] Define the Erlang/OTP version
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
  
    - name: Release
      run: |
        mix compile
        mix assets.deploy
        mix phx.digest
        mix release --overwrite
      env:
        MIX_ENV: 'prod'
  
    - name: Deploy to server
      run: |
        mkdir ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
        sudo chmod 600 ~/.ssh/private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        echo "Release created at $(date +'%Y-%m-%dT%H:%M:%S')" > _build/prod/rel/famdash/deploy_marker
        rsync -avz -e "ssh -i ~/.ssh/private.key" _build/prod/rel/famdash/ devops@$SERVER_IP:/opt/famdash/
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
        SERVER_IP: ${{secrets.SERVER_IP}}
    
